stages:
  - build-package

debian:
  stage: build-package
  needs: []
  image:
    name: debian:trixie-backports
    pull_policy: if-not-present
  artifacts:
    when: always
    paths: [ packages/Debian/docker-backup.deb ]
  # before_script:
  #   - apk add curl
  script:
    - mkdir -p packages/Debian/docker-backup/usr/bin
    - mv docker-backup.py packages/Debian/docker-backup/usr/bin/docker-backup
    - echo "Setting Permissions"
    - chmod +x packages/Debian/docker-backup/usr/bin/docker-backup
    - chmod 755 packages/Debian/docker-backup/DEBIAN -R
    - echo "Creating Deb Package"
    - dpkg-deb --root-owner-group --build packages/Debian/docker-backup docker-backup.deb

