stages:
  - build-package

debian:
  stage: build-package
  needs: []
  image:
    name: debian:trixie-backports
    pull_policy: if-not-present
  artifacts:
    when: always
    paths: [ packages/Debian/docker-backup/docker-backup.deb ]
  # before_script:
  #   - apk add curl
  script:
    - ls
    - mkdir -p packages/Debian/docker-backup/usr/bin
    - mv docker-backup.py packages/Debian/docker-backup/usr/bin/docker-backup
    - chmod +x packages/Debian/docker-backup/usr/bin/docker-backup
    - cd packages/Debian/
    - dpkg-deb --root-owner-group --build docker-backup

