name: Pylint

on: [push]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: PyLint with dynamic badge
        uses: Silleellie/pylint-github-action@v3
        with:
          lint-path: docker-backup.py  # lint src package
          python-version: 3.14  # python version which will lint the package
